### ISSUE TITLE
Maintaining position information?

### ISSUE THREAD

**Issue by rtm** [remarkjs/remark-highlight.js#30]
Do you have any thoughts on the best way to maintain position (line, column) information in the individual leaf nodes?

**Comment by wooorm** [comment]
@rtm How do you mean? Do you mean on the HAST nodes that come from lowlight?

**Comment by wooorm** [comment]
Closing due to no response and I’m not sure what you’re asking. Feel free to comment here if it’s still an issue and we’ll reopen it.
