### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by devpixde** [remarkjs/remark-highlight.js#33]
I try to run basic example:

            const unified = require('unified')
            const markdown = require('remark-parse')
            const html = require('remark-html')
            const highlight = require('remark-highlight.js')

            let css = `~~~css
            h1 {
                color: red;
            }
            `;

            unified()
                .use(markdown)
                .use(highlight)
                .use(html)
                .process(css, (err, file) => {
                    console.log(String(file))
                })

But output is still:

```
<pre><code class="language-css">        h1 {
            color: red;
        }   
</code></pre>
```

so hljs classes are missing. Whats going wrong?
Testet in latest chrome.

**Comment by wooorm** [comment]
I cannot reproduce it, your example works for me:

```javascript
const unified = require('unified')
const markdown = require('remark-parse')
const html = require('remark-html')
const highlight = require('remark-highlight.js')


let css = `~~~css
h1 {
    color: red;
}
`;

unified()
    .use(markdown)
    .use(highlight)
    .use(html)
    .process(css, (err, file) => {
        console.log(String(file))
    })
```

Yields:

```html
<pre><code class="hljs language-css"><span class="hljs-selector-tag">h1</span> {
    <span class="hljs-attribute">color</span>: red;
}
</code></pre>
```

You removed the issue template when raising this question: it’s there for a reason, so we can help you better. Please take the time to fill out issues properly.

**Comment by devpixde** [comment]
I must apologize for not following the official way. I try to us remark with highlight within a vuejs component. I built a very basic example but its still not working (hljs classes are not added).
I am sure i missed something but can't figure out whats wrong.
Sample project:
https://github.com/devpixde/remark-test
Running test:
https://devpixde.github.io/remark-test/

**Comment by wooorm** [comment]
Thanks for making this example, that really helps, I was able to debug what’s going on.

Typically, you can require this package, and you’ll get the [`dist` build](https://github.com/remarkjs/remark-highlight.js/blob/c1b56187fc6d018f89b76c63da2847e2d53b8f96/package.json#L26), and everything works fine.

Webpack in Vue seems to be configured to load [modules](https://github.com/remarkjs/remark-highlight.js/blob/c1b56187fc6d018f89b76c63da2847e2d53b8f96/package.json#L27), in which case you get an exported object.

For this, you can either import the module (`import highlight from "remark-highlight.js"`), or use the `default` prop when `require`ing: `const highlight = require("remark-highlight.js").default`

I went with `.default`, and that fixes it for you in Vue!

Note, you may be better off using [remark-rehype](https://github.com/remarkjs/remark-rehype), [rehype-highlight](https://github.com/rehypejs/rehype-highlight), and finally using [`hast-to-hyperscript`](https://github.com/syntax-tree/hast-to-hyperscript) to transform hast into Vue elements!

Read more about unified on its [website](https://unifiedjs.com) or in its [readme](https://github.com/unifiedjs/unified).

Good luck!
