### ISSUE TITLE
Not working with Next Js SSG

### ISSUE THREAD

**Issue by MejanH** [remarkjs/remark-highlight.js#35]
I created my blog by following the nextjs.org docs. Is it because of Typescript?

Here is my code

```
  const processedContent = await remark()
    .use(highlight)
    .use(html)
    .process(matterResult.content);
```
no error, no highlighting, nothing...

**Comment by ChristianMurphy** [comment]
@MejanH Please follow the issue template for bug reports, and direct questions to [Spectrum](https://spectrum.chat/unified/remark).

> Is it because of Typescript?

If it was TypeScript related there would likely be a build error or a runtime error.

More likely it because `remark()` both input and output markdown, it looks like you want markdown in and HTML out.
Have you tried the example from the readme which outputs HTML?

```ts
import * as unified from 'unified'
import * as markdown from 'remark-parse'
import * as html from 'remark-html'
import * as highlight from 'remark-highlight.js'

const processedContent = unified()
  .use(markdown)
  .use(highlight)
  .use(html)
  .process(matterResult.content)
```

If you have follow up questions, feel free to reach out on https://spectrum.chat/unified/remark

**Comment by MejanH** [comment]
still not working. tried with `unified()`, `remark-parse`. but still, nothing is happening. 

Should I add some classes in dangerouslySetInnerHtml? I didn't add any class or styles though.

**Comment by wooorm** [comment]
I just confirmed that the example by @ChristianMurphy, and the one in the readme, both work.

Your problem seems to relate to Next. We don’t work on Next.

**Comment by MejanH** [comment]
when I added CSS from `highlight.js` from `node_modules` folder it seems to be work only for Js though. if it is the method to get this plugin working, I think docs should be updated for newcomers like me.

**Comment by wooorm** [comment]
> it seems to be work only for Js though

Can you expand on what do you mean? I don’t understand.

**Comment by MejanH** [comment]
Sorry, Please forgive my rude comments from the start. it's really working awesome. Looks like I didn't know how to work with SSG. I am a self-taught programmer, I only learn by researching on the web. Thank you so much for your time. 

**I didn't know to highlight code I have to mention language name after backticks in MD**
**I didn't know I have to import the CSS file for syntax highlighting**

This plugin is amazing. It was my fault.

**Comment by wooorm** [comment]
Thank you for your kind words Mejan! You know, open source can be a pretty nice place: creating code together. But there’s also lots of folks who don‘t respect the time of maintainers.  We maintainers see lots of issues per day—lots of folks that want our attention. A couple nice words, and spending some extra time on your question, really makes our day and makes sure we can help better!

**Comment by hallaji** [comment]
For everyone landing here, you need to install [highlight.js](https://github.com/highlightjs/highlight.js) alongside`
remark-highlight.js` package in order to load styles and register required languages.

**Comment by farzadso** [comment]
> For everyone landing here, you need to load styles from a CDN or install [highlight.js](https://github.com/highlightjs/highlight.js) alongside` remark-highlight.js` package in order to load styles.

And if anyone is wondering how to add the styles after adding the package, this link can help:

https://nextjs.org/docs/basic-features/built-in-css-support

Something like this in your components/routes:

```js
import 'highlight.js/styles/default.css'
```

You can also replace `default.css` with whichever theme you like.
