### ISSUE TITLE
 Unknown language: `j` is not registered

### ISSUE THREAD

**Issue by Prottoy2938** [remarkjs/remark-highlight.js#36]
Can't do live highlighting.

I'm working a project that allows user to write markdown and do a preview of it as they are writing.

To do the writing, I'm using `monaco` editor, the application gets the markdown output from there and passes it down to the `ReactMarkdown` like this:

```jsx
    <ReactMarkdown plugins={[gfm, markdownHighlight]} skipHtml={true}>
       {content}
    </ReactMarkdown>
```

So the application does live preview as the user types.

So when the user trys to write a code block, first they do `'```'` and then they specify the language like this `'```jsx'`.

Here where the error occurs, as soon as the user types the word `j` to specify the language, the app crashes. Showing this error:

> Unhandled Runtime Error
Error: Unknown language: `j` is not registered

Any help on that?

**Comment by ChristianMurphy** [comment]
@Prottoy2938 this isn't really a bug.
`j` isn't a language supported by highlight js, the error is correct.

For live editing consider wrapping a try/catch block around the code and/or using an error boundary https://reactjs.org/docs/error-boundaries.html

Also be aware the issue tracker is for bugs/issues and is used as a backlog for changes, questions will be closed as they aren't part of the backlog.
Please direct questions to https://github.com/remarkjs/remark/discussions which allows for a more conversational format.
Thanks!
